### ISSUE TITLE
[Docs]: Helm install with values.yaml only and initialise encryption variables

### ISSUE THREAD

**Issue by sum35h** [appsmithorg/appsmith-docs#1248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem and improvement.

The helm install instructions need to be updated such that users always use the values.yaml instead of passing run time arguments, which users loose track of.
The users will also need to set the encryption variables in values.yaml when first installing Appsmith helm chart.

**Comment by jnikhila** [comment]
@sum35h - For installation to work seamless for our users, the encryption variables should be set up by Appsmith and not be user-driven. As part of this ticket, we can make the changes for values.yaml on docs. However, DevOps should handle the encrption variable set up internally so that user actions are not needed. CC: @pratapaprasanna
