### ISSUE TITLE
[Docs]: Feedback Widget - Inline comments

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#1736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

NA

### Describe the problem and improvement.

- Add a textbox to capture comments
- Add a button to submit the comments
- Show the textbox and button, only after the user selects thumbs down.

**Comment by dgarcia360** [comment]
Hi! I found this issue while searching for "feedback widget" on GitHub.

I'm building [PushFeedback](https://pushfeedback.com), a feedback widget tailored for docs sites that integrates well with Docusaurus.

![ezgif-1-7ede30badd](https://github.com/pypa/pip/assets/9107969/5fd7e6ff-607f-4baa-987a-1660662d080a)

> Show the textbox and button, only after the user selects thumbs down.

I think it could fit your use case since widget can be [triggered from any button](https://docs.pushfeedback.com/configuration/layout#add-the-widget-to-any-button
) once the user select the thumbs down icon.

We have a free plan open-source project in exchange of keeping the widget branding. If you're interested in exploring integrating PushFeedback, please [sign up for an account](https://app.pushfeedback.com/accounts/signup/) and let me know to remove the limitations for your project. 

Additionally, I'd be more than happy to assist with a pull request to integrate the [Docusaurus extension](https://docs.pushfeedback.com/installation/docusaurus).

**Comment by vasanthappsmith** [comment]
[Figma](https://www.figma.com/file/Yc4kKCiCeaTSL9VjWEG021/docs?type=design&node-id=96-2581&mode=design&t=XzHL0m5AQ24oPkEC-4)

**Comment by jnikhila** [comment]
@vasanthappsmith - as per our discussion, could you please update the designs?

**Comment by jnikhila** [comment]
#1844
