### ISSUE TITLE
[Docs]: APPSMITH_REDIS_URL

### ISSUE THREAD

**Issue by mehaase** [appsmithorg/appsmith-docs#1847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/getting-started/setup/instance-configuration/custom-mongodb-redis#external-redis

### Describe the problem and improvement.

This page explains how to run a Docker setup with a separate Redis container. It says to define the environment variable `APPSMITH_REDIS_URL` but I think it should be `APPSMITH_REDIS_URI`?

**Comment by pratapaprasanna** [comment]
hey @mehaase , 
thankyou for reaching out to us about this.

In appsmith we prefer using `APPSMITH_REDIS_URL` to `APPSMITH_REDIS_URI`

**Comment by mehaase** [comment]
Okay but when I set APPSMITH_REDIS_URL it doesn't work, and the monogdb variable ends with _URI not _URL. Are you sure you have the right variable name?

**Comment by pratapaprasanna** [comment]
Ok interesting, can you share the logs when it didn't work.
Also, mongo_db ends with URI and redis ends with url because URI which is often an identifier we have username and password in the URI
But, in redis we donot have any username and password and therefore it will be an URL (where we connect to the cluster)
