### ISSUE TITLE
[Docs]: Updating Google & Github SSO documentation

### ISSUE THREAD

**Issue by pranayagarwal96** [appsmithorg/appsmith-docs#506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/getting-started/setup/instance-configuration/authentication/google-login

### Discord/slack/intercom Link

https://theappsmith.slack.com/archives/CGBPVEJ5C/p1666768301142219

### Describe the problem

The last step in docs page for Google/ Github SSO requires user to insert the Client ID and Client Secret in the docker image whereas currently the last step is to insert the Client ID and Client Secret in the instance itself. And this doc is linked to home page for setting-up Google/ Github SSO within the instance, and hence can create confusion among users.
 

### Describe the improvement

Should replace the last step in docs page to show that Client ID and Client Secret should be inserted in the instance itself

### Why do you think this change is needed?

This will avoid confusion among users trying to set-up SSO via Google/ Github

**Comment by jnikhila** [comment]
@pranayagarwal96 - The information is available on the [doc](https://docs.appsmith.com/getting-started/setup/instance-configuration/authentication/google-login)[point 5. Update the instance configuration with the following fields]. Could you please verify and update us?

**Comment by pranayagarwal96** [comment]
@infinitetrooper just tagging you here, can you go through this issue once, and see if it makes sense?

**Comment by infinitetrooper** [comment]
Sure @pranayagarwal96  - I will check this early next week and update here.

**Comment by infinitetrooper** [comment]
@jnikhila  - I think the issue is that the Instance Configuration can now happen from UI (under admin settings). They don't need to update the docker file directly. This would be an easy way to enable OAuth and we should show the UI way to update the variables. Images below

<img width="1440" alt="Screenshot 2023-01-18 at 3 30 54 PM" src="https://user-images.githubusercontent.com/16632903/213142574-67f21058-6d30-43bb-b26c-2c8b451cd1e9.png">
<img width="1440" alt="Screenshot 2023-01-18 at 3 31 02 PM" src="https://user-images.githubusercontent.com/16632903/213142586-02c04527-14b8-482f-899a-93303ace8df2.png">
