### ISSUE TITLE
[Docs]: MySQL SQL mode and its impact

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith-docs#622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/issues/18447

### Release Date

December 9, 2022

### First Draft

https://www.notion.so/appsmith/MySQL-SQL-Mode-and-its-impact-08b75593714c40a09ec0e77cf8c2fe4c

### Loom video

N/A

### Discord/slack/intercom Link if needed

https://theappsmith.slack.com/archives/C01CFTXD0N8/p1669634346600169

### Use cases or user requests

SQL mode (sql_mode) is one of the system variables of MySQL. Through this variable, the MySQL Server SQL mode is controlled. Many operational characteristics of MySQL Server can be configured by setting the SQL mode. By setting the SQL mode appropriately, a client program can instruct the server on how strict or forgiving to be about accepting input data, enable or disable behaviors relating to standard SQL conformance, or provide better compatibility with other database systems. 

## What are the implications of sql_mode?

By default, the server uses an `sql_mode` value of  `''`  (the empty string), which enables no restrictions. Thus, the server operates in forgiving mode (non-strict mode) by default. In non-strict mode, the MySQL server converts erroneous input values to the closest legal values (as determined from column definitions) and continues on its way. For example, if you attempt to store a negative value into an `UNSIGNED` column, MySQL converts it to zero, which is the nearest legal value for the column.

**Comment by jnikhila** [comment]
@harshilp24 - We need to add information in the [MySQL docs - Querying MySQL](https://docs.appsmith.com/reference/datasources/querying-mysql#querying-mysql) section.

As quoted by @subrata71 

> Let’s say you have a table named employee which has column named salary of type SHORTINT in MySQL.
Employee
employee_id     name       salary
AP001           John        32767
AP002           Walker      3323
It’s time for John to get an increment. The company decides to raise John’s salary by 500. Now it’s been approved! :smile:
It’s time to update the salary in the DB.
Let’s set the sql mode to non-strict mode before updating the salary of John.
SET sql_mode = '';
UPDATE employee SET salary = salary + 500 WHERE employee_id = 'AP001' and name = 'John';
But unfortunately the salary of John remains the same i.e. 32767 . 
Because SHORTINT in MySQL can have minimum value as -32768 and maximum value as 32767.
As 32767 + 500 results in an overflow it keeps the maximum that it can hold i.e. 32767. This happened silently because of the non-strict sql mode. Now, if you try to update the salary under strict mode then this update query will fail and show a message related to overflow. It won’t let you update.
User can set the strict mode using `SET sql_mode`.

CC: @subrata71 - Please add/update if I've missed something. @danciaclara - FYI.
